all:
  children:
    proxy:
      hosts:
        proxy:
          ansible_connection: docker
    app:
      hosts:
        app:
          ansible_connection: docker
    database:
      hosts:
        db:
          ansible_connection: docker
