all:
  children:
    proxy:
      hosts:
        proxy_container:
          ansible_connection: community.docker.docker
          ansible_host: proxy
          ansible_python_interpreter: /usr/bin/python3
    app:
      hosts:
        app_container:
          ansible_connection: community.docker.docker
          ansible_host: app
          ansible_python_interpreter: /usr/bin/python3
    database:
      hosts:
        db_container:
          ansible_connection: community.docker.docker
          ansible_host: db
          ansible_python_interpreter: /usr/bin/python3
